
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Sub Kegiatan      <small><?= cclang('detail', ['Sub Kegiatan']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/sub_kegiatan'); ?>">Sub Kegiatan</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Sub Kegiatan</h3>
                     <h5 class="widget-user-desc">Detail Sub Kegiatan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_sub_kegiatan" id="form_sub_kegiatan" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($sub_kegiatan->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kegiatan </label>

                        <div class="col-sm-8">
                           <?= _ent($sub_kegiatan->kegiatan_nama_kegiatan); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sub Kegiatan </label>

                        <div class="col-sm-8">
                           <?= _ent($sub_kegiatan->sub_kegiatan); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Bagian </label>

                        <div class="col-sm-8">
                           <?= _ent($sub_kegiatan->masterbagian_nama_bagian); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pagu Anggaran </label>

                        <div class="col-sm-8">
                           <?= _ent($sub_kegiatan->pagu_anggaran); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('sub_kegiatan_update', function() use ($sub_kegiatan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit sub_kegiatan (Ctrl+e)" href="<?= site_url('administrator/sub_kegiatan/edit/'.$sub_kegiatan->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Sub Kegiatan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/sub_kegiatan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Sub Kegiatan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>