
<!--<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>-->
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.

</script>
<!-- Content Header (Page header) -->
<section class="content-header">
    
   <h1>
      Priviu Cetak     
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/register_spj'); ?>">Register SPJ</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                                          
                     <!--<div class="widget-user-image">-->
                     <!--   <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">-->
                     <!--</div>-->
                     <!-- /.widget-user-image -->
                     <!--<h3 class="widget-user-username">Register SPJ</h3>-->
                     <!--<h5 class="widget-user-desc">Detail Register SPJ</h5>-->
                     
                     <div class="row pull-right">
       
            <!-- Tombol Cetak -->
    <button id="printButton" onclick="printDiv()" class="btn btn-danger"><i class="fa fa-print "></i> Print</button>
    
           </div>
           <br>
           <hr>
                 
                  
                 
           

                 
                 <?php
                 
                 include "register_spj_previu.php";
                 ?>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>