
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Register SPJ      <small><?= cclang('detail', ['Register SPJ']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/register_spj'); ?>">Register SPJ</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Register SPJ</h3>
                     <h5 class="widget-user-desc">Detail Register SPJ</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_register_spj" id="form_register_spj" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Bagian </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->masterbagian_nama_bagian); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sub Kegiatan </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->sub_kegiatan_sub_kegiatan); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Spj </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->no_spj); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Pengajuan </label>

                        <div class="col-sm-8">
                           <?= _ent(tanggal_indo($register_spj->tanggal_pengajuan)); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Pengajuan </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->jenis_pengajuan_jenis_pengajuan); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nominal </label>

                        <div class="col-sm-8">
                           <?= _ent(currency_format($register_spj->nominal)); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group " style="display:none">
                        <label for="content" class="col-sm-2 control-label">No Pengantar </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->no_pengantar); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group " style="display:none">
                        <label for="content" class="col-sm-2 control-label">Tanggal Bku </label>

                        <div class="col-sm-8">
                           <?= _ent(tanggal_indo($register_spj->tanggal_bku)); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Spp </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->no_spp); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Spp </label>

                        <div class="col-sm-8">
                           <?= _ent(tanggal_indo($register_spj->tanggal_spp)); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Spm </label>

                        <div class="col-sm-8">
                           <?= _ent($register_spj->no_spm); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Spm </label>

                        <div class="col-sm-8">
                           <?= _ent(tanggal_indo($register_spj->tanggal_spm)); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Pengembalian </label>

                        <div class="col-sm-8">
                           <?= _ent(tanggal_indo($register_spj->tanggal_pengembalian)); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('register_spj_update', function() use ($register_spj){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit register_spj (Ctrl+e)" href="<?= site_url('administrator/register_spj/edit/'.$register_spj->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Register Spj']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/register_spj/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Register Spj']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>