
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
 <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
//   // Binding keys
//   $('*').bind('keydown', 'Ctrl+a', function assets() {
//       window.location.href = BASE_URL + '/administrator/Verifikasi/add';
//       return false;
//   });

//   $('*').bind('keydown', 'Ctrl+f', function assets() {
//       $('#sbtn').trigger('click');
//       return false;
//   });

//   $('*').bind('keydown', 'Ctrl+x', function assets() {
//       $('#reset').trigger('click');
//       return false;
//   });

//   $('*').bind('keydown', 'Ctrl+b', function assets() {

//       $('#reset').trigger('click');
//       return false;
//   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('verifikasi') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('verifikasi') ?></li>
   </ol>
</section>
<br>


<?php is_allowed('verifikasi_add', function() use ($register) {?>
<!-- Main content -->
<section class="content" style="min-height: 10px;">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning collapsed-box ">
                <div class="box-header with-border">
                   <button type="button" class="btn btn-box-tool" data-widget="collapse"> <h3 class="box-title">Tambahkan Catatan</h3></button>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">Tambahkan Disini &nbsp;<i class="fa fa-plus"></i></button>
                    </div>
                </div>
                
                <div class="box-body ">
                    <div class="box box-widget widget-user-2">
                        <?= form_open('', [
                            'name'    => 'form_verifikasi', 
                            'class'   => 'form-horizontal form-step', 
                            'id'      => 'form_verifikasi', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                        ]); ?>
                        <?php
                        $user_groups = $this->model_group->get_user_group_ids();
                        ?>
                        
                        <div class="form-group">
                            <label for="spj" class="col-sm-2 control-label">No Urut SPJ 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select class="form-control chosen chosen-select-deselect" name="spj" id="spj" data-placeholder="Select Spj">
                                    <option value="<?= $register->id ?>" selected><?= $register->no_spj; ?></option>
                                </select>
                                <small class="info help-block"></small>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="verifikator" class="col-sm-2 control-label">Tanggal</label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" name="tanggal" id="tanggal" placeholder="Tanggal">
                                <small class="info help-block"></small>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="uraian" class="col-sm-2 control-label">Uraian <i class="required">*</i></label>
                            <div class="col-sm-8">
                                <textarea id="uraian" name="uraian" rows="5" class="textarea form-control"><?= set_value('uraian'); ?></textarea>
                                <small class="info help-block"></small>
                            </div>
                        </div>
                        
                        
                         <div class="form-group ">
                            <label for="dicukupi" class="col-sm-2 control-label">Dicukupi 
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select" name="dicukupi" id="dicukupi" data-placeholder="Select Dicukupi" >
                                    <option value=""></option>
                                    <option  value="Ya">Ya</option>
                                    <option  value="Belum">Belum</option>
                                    </select>
                                <small class="info help-block">
                                </small>
                            </div>
                        </div>
                        
                        <div class="message"></div>
                        <div class="row-fluid col-md-7 container-button-bottom">
                            <a class="btn btn-flat btn-info btn_save btn_action btn_save_back" id="btn_save" data-stype='back' title="<?= cclang('save_and_go_the_list_button'); ?> (Ctrl+d)">
                                <i class="ion ion-ios-list-outline"></i> <?= cclang('tambahkan'); ?>
                            </a>
                            <span class="loading loading-hide">
                                <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> 
                                <i><?= cclang('loading_saving_data'); ?></i>
                            </span>
                        </div>
                        <?= form_close(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php }) ?>

<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        
                        <!--<a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('verifikasi')]); ?>  (Ctrl+a)" href="<?=  site_url(); ?>administrator/verifikasi/add/<?= $id_spj ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('verifikasi')]); ?></a>-->
                        
                        <?php is_allowed('verifikasi_export', function(){?>
                        <!--<a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('verifikasi') ?> " href="<?= site_url('administrator/verifikasi/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>-->
                        <?php }) ?>
                        <?php is_allowed('verifikasi_export', function(){?>
                        <!--<a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('verifikasi') ?> " href="<?= site_url('administrator/verifikasi/export_pdf?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>-->
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('verifikasi') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('verifikasi')]); ?>  <i class="label bg-yellow"><?= $verifikasi_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_verifikasi" id="form_verifikasi" action="<?= base_url('administrator/verifikasi/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="spj"data-sort="1" data-primary-key="0"> <?= cclang('no_urut_spj') ?></th>
                                                     <th data-field="verifikator"data-sort="1" data-primary-key="0"> <?= cclang('verifikator') ?></th>
                                                    <th>Tanggal Veifikasi</th>
                           <th data-field="uraian"data-sort="1" data-primary-key="0"> <?= cclang('uraian') ?></th>
                           <th data-field="dicukupi"data-sort="1" data-primary-key="0"> <?= cclang('dicukupi') ?></th>
                           <th>Tindak Lanjut BPP</th>
                           <th>Keterangan</th>
                          
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_verifikasi">
                     <?php foreach($verifikasis as $verifikasi): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $verifikasi->id; ?>">
                           </td>
                                                       
                           <td><?php if  ($verifikasi->spj) {

                              echo anchor('administrator/register_spj/view/'.$verifikasi->spj.'?popup=show', $verifikasi->register_spj_no_spj, ['class' => 'popup-view']); }?> </td>
                            <td><?= _ent($verifikasi->full_name); ?>(<?= $verifikasi->name_grup ?>)</td> 
                            <td><?= _ent(tanggal_indo($verifikasi->tanggal)); ?></td>  
                           <td><?= _ent($verifikasi->uraian); ?></td> 
                           <td>
                               <?php if($verifikasi->dicukupi=='Ya'):?>
                               <i class="fa fa-check text-green"></i>
                               <?php endif; ?>
                               
                               </td> 
                              <td><?= $verifikasi->tindak_lanjut ?></td> 
                              <td><?= $verifikasi->keterangan ?></td> 
                           
                           <td width="200">
                               <?php is_allowed('verifikasi_tindaklanjut', function() use ($verifikasi){?>
                                 <a href="<?= site_url('administrator/verifikasi/tindaklanjut/' .$verifikasi->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('Tindak Lanjut') ?>
                              <!--<a href="<?= site_url('administrator/verifikasi/view/' . $verifikasi->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>-->
                              <?php }) ?>
                               <?php if(($verifikasi->verifikator == $this->aauth->get_user_id()) OR ($this->aauth->is_member('ppk skpd'))) :?>
                            
                                                              
                              <?php is_allowed('verifikasi_update', function() use ($verifikasi){?>
                              <a href="<?= site_url('administrator/verifikasi/edit/' . $verifikasi->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('verifikasi_delete', function() use ($verifikasi){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/verifikasi/delete/' . $verifikasi->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                                <?php endif; ?>
                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($verifikasi_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Verifikasi SPJ data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               
               <!-- /.widget-user -->
               <div class="row">
                   <div class="col-md-8">
                   <div class="col-sm-2 padd-left-0 ">
                        <!--<a href="<?= base_url() ?>administrator/<?= $this->session->modul ?>" type="button" class="btn btn-warning"  title="Kembali ke daftar SPJ">Kembali</a>-->
                        <a href="<?= $back_url ?>" type="button" class="btn btn-warning"  title="Kembali ke daftar SPJ">Kembali</a>
                     </div>
                     </div>
               </div>
               <!--<div class="row">-->
               <!--   <div class="col-md-8">-->
               <!--      <div class="col-sm-2 padd-left-0 " >-->
               <!--         <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >-->
               <!--            <option value="">Bulk</option>-->
               <!--                                      <option value="delete">Delete</option>-->
               <!--                                   </select>-->
               <!--      </div>-->
               <!--      <div class="col-sm-2 padd-left-0 ">-->
               <!--         <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>-->
               <!--      </div>-->
               <!--      <div class="col-sm-3 padd-left-0  " >-->
               <!--         <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">-->
               <!--      </div>-->
               <!--      <div class="col-sm-3 padd-left-0 " >-->
               <!--         <select type="text" class="form-control chosen chosen-select" name="f" id="field" >-->
               <!--            <option value=""><?= cclang('all'); ?></option>-->
               <!--             <option <?= $this->input->get('f') == 'spj' ? 'selected' :''; ?> value="spj">Spj</option>-->
               <!--            <option <?= $this->input->get('f') == 'uraian' ? 'selected' :''; ?> value="uraian">Uraian</option>-->
               <!--            <option <?= $this->input->get('f') == 'dicukupi' ? 'selected' :''; ?> value="dicukupi">Dicukupi</option>-->
               <!--            <option <?= $this->input->get('f') == 'verifikator' ? 'selected' :''; ?> value="verifikator">Verifikator</option>-->
               <!--           </select>-->
               <!--      </div>-->
               <!--      <div class="col-sm-1 padd-left-0 ">-->
               <!--         <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">-->
               <!--         Filter-->
               <!--         </button>-->
               <!--      </div>-->
               <!--      <div class="col-sm-1 padd-left-0 ">-->
               <!--         <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/verifikasi');?>" title="<?= cclang('reset_filter'); ?>">-->
               <!--         <i class="fa fa-undo"></i>-->
               <!--         </a>-->
               <!--      </div>-->
               <!--   </div>-->
               <!--   </form>                  <div class="col-md-4">-->
               <!--      <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >-->
               <!--         <?= $pagination; ?>-->
               <!--      </div>-->
               <!--   </div>-->
               <!--</div>-->
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->



<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_verifikasi').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/verifikasi/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('verifikasi', $('table.dataTable'));
  }); /*end doc ready*/
</script>


<script>
    $(document).ready(function(){

                          
      
    
      $('.btn_save').click(function(){
        $('.message').fadeOut();
            
        var form_verifikasi = $('#form_verifikasi');
        var data_post = form_verifikasi.serializeArray();
        var save_type = $(this).attr('data-stype');

        data_post.push({name: 'save_type', value: save_type});
    
        $('.loading').show();
    
        $.ajax({
          url: BASE_URL + '/administrator/verifikasi/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
            
            if (save_type == 'back') {
              window.location.href = res.redirect;
              return;
            }
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/
      
       
 
       

      
    
    
    }); /*end doc ready*/
</script>