
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Masterbagian/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('masterbagian') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('masterbagian') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('masterbagian_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('masterbagian')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/masterbagian/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('masterbagian')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('masterbagian_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('masterbagian') ?> " href="<?= site_url('administrator/masterbagian/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('masterbagian_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('masterbagian') ?> " href="<?= site_url('administrator/masterbagian/export_pdf?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('masterbagian') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('masterbagian')]); ?>  <i class="label bg-yellow"><?= $masterbagian_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_masterbagian" id="form_masterbagian" action="<?= base_url('administrator/masterbagian/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="nama_bagian"data-sort="1" data-primary-key="0"> <?= cclang('nama_bagian') ?></th>
                           <th data-field="bpp"data-sort="1" data-primary-key="0"> <?= cclang('bpp') ?></th>
                           <th data-field="pptk"data-sort="1" data-primary-key="0"> <?= cclang('pptk') ?></th>
                           <th data-field="verifikator"data-sort="1" data-primary-key="0"> <?= cclang('verifikator') ?></th>
                           <th data-field="verifikator2"data-sort="1" data-primary-key="0"> <?= cclang('verifikator2') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_masterbagian">
                     <?php foreach($masterbagians as $masterbagian): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $masterbagian->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($masterbagian->nama_bagian); ?></td> 
                           <td><?php if  ($masterbagian->bpp) {

                              echo anchor('administrator/user_bpp/view/'.$masterbagian->bpp.'?popup=show', $masterbagian->user_bpp_full_name, ['class' => 'popup-view']); }?> </td>
                             
                           <td><?= join_multi_select($masterbagian->pptk, 'user_pptk', 'id', 'full_name'); ?></td> 
                           <td><?php if  ($masterbagian->verifikator) {

                              echo anchor('administrator/v_verifikator/view/'.$masterbagian->verifikator.'?popup=show', $masterbagian->v_verifikator_full_name, ['class' => 'popup-view']); }?> </td>
                             
                           <td><?php if  ($masterbagian->verifikator2) {

                              echo anchor('administrator/v_verifikator2/view/'.$masterbagian->verifikator2.'?popup=show', $masterbagian->v_verifikator2_full_name, ['class' => 'popup-view']); }?> </td>
                             
                           <td width="200">
                            
                                                              <?php is_allowed('masterbagian_view', function() use ($masterbagian){?>
                                 <a href="<?= site_url('administrator/masterbagian/single_pdf/' .$masterbagian->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/masterbagian/view/' . $masterbagian->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('masterbagian_update', function() use ($masterbagian){?>
                              <a href="<?= site_url('administrator/masterbagian/edit/' . $masterbagian->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('masterbagian_delete', function() use ($masterbagian){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/masterbagian/delete/' . $masterbagian->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($masterbagian_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Bagian data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'nama_bagian' ? 'selected' :''; ?> value="nama_bagian">Nama Bagian</option>
                           <option <?= $this->input->get('f') == 'bpp' ? 'selected' :''; ?> value="bpp">Bpp</option>
                           <option <?= $this->input->get('f') == 'pptk' ? 'selected' :''; ?> value="pptk">Pptk</option>
                           <option <?= $this->input->get('f') == 'verifikator' ? 'selected' :''; ?> value="verifikator">Verifikator</option>
                           <option <?= $this->input->get('f') == 'verifikator2' ? 'selected' :''; ?> value="verifikator2">Verifikator2</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/masterbagian');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_masterbagian').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/masterbagian/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('masterbagian', $('table.dataTable'));
  }); /*end doc ready*/
</script>