
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Bantuan/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('bantuan') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('helpdesk') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
  <div class="col-md-12">
    <div class="widget-user-header text-right" style="margin-bottom:25px;">
        <?php is_allowed('bantuan_add', function(){?>
        <a class="btn btn-flat btn-success btn_add_new" 
           id="btn_add_new" 
           title="Ajukan Pertanyaan" 
           href="<?= site_url('administrator/bantuan/add'); ?>">
           <i class="fa fa-plus-square-o"></i> Ajukan Pertanyaan
        </a>
        <?php }) ?>
    </div>
  </div>
</div>
     <div class="row" >
      
      <div class="col-md-12">
          
         
          
          
          
          <form name="form_bantuan" id="form_bantuan" action="<?= base_url('administrator/bantuan/index'); ?>">
          
        <ul class="timeline">
            <?php 
    $last_date = null; // penanda tanggal terakhir
    foreach($bantuans as $bantuan): 
        $current_date = date('Y-m-d', strtotime($bantuan->waktu)); 
    ?>
        <?php if ($current_date != $last_date): ?>
            <!-- timeline time label -->
            <li class="time-label">
                <span class="bg-red">
                    <?= tanggal_indonesia($bantuan->waktu,false); ?>
                </span>
            </li>
            <!-- /.timeline-label -->
            <?php $last_date = $current_date; ?>
        <?php endif; ?>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-user bg-aqua"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> <?= jam_indonesia($bantuan->waktu,false) ?></span>

                <h3 class="timeline-header"><a href="#"><?= $bantuan->full_name ?></a> mengatakan.....</h3>
                

                <div class="timeline-body">
                    <h3 class="timeline-header"><?= _ent($bantuan->judul); ?></h3>
                  <?= _ent($bantuan->konten); ?>
                </div>
                <div class="timeline-footer">
                  <!--<a class="btn btn-primary btn-xs">0 tanggapan</a>-->
                  
                  <?php $jml_komen = $this->model_bantuan->komentar_count($bantuan->id); ?>
                    <a class="btn btn-primary btn-xs" href="<?= site_url('administrator/bantuan/view/'.$bantuan->id); ?>">
                      <?= $jml_komen; ?> tanggapan
                    </a>

                  <!--<a class="btn btn-danger btn-xs">Delete</a>-->
               
                  
                 <!--<?php is_allowed('bantuan_view', function() use ($bantuan){?>-->
                 <!--             <a href="<?= site_url('administrator/bantuan/view/' . $bantuan->id); ?>" class="btn btn-warning btn-xs"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>-->
                 <!--             <?php }) ?>-->
                
                   <!--<?php is_allowed('bantuan_delete', function() use ($bantuan){?>-->
                   <!--           <a href="javascript:void(0);" data-href="<?= site_url('administrator/bantuan/delete/' . $bantuan->id); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>-->
                   <!--            <?php }) ?>-->
                   
                   
                   
                   
                     <?php 
                    $current_user_id = get_user_data('id'); // Aauth helper ambil id user aktif
                    if ($bantuan->user == $current_user_id): ?>
                        <a href="<?= site_url('administrator/bantuan/edit/' . $bantuan->id); ?>" 
                           class="btn btn-success btn-xs">
                           <i class="fa fa-edit"></i>  <?= cclang('update_button'); ?>
                        </a>
                    <?php endif; ?>
                    
                    
                    
                    
                   <?php 
                    $current_user_id = get_user_data('id'); // Aauth helper ambil id user aktif
                    if ($bantuan->user == $current_user_id): ?>
                        <a href="javascript:void(0);" 
                           data-href="<?= site_url('administrator/bantuan/delete/' . $bantuan->id); ?>" 
                           class="btn btn-danger btn-xs remove-data">
                           <i class="fa fa-close"></i> <?= cclang('remove_button'); ?>
                        </a>
                    <?php endif; ?>
                </div>
              </div>
            </li>
            <!-- END timeline item -->
            <!-- timeline item -->
            
           <?php endforeach; ?>
                      <?php if ($bantuan_counts == 0) :?>
                         
                        <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-red">
                    <?= tanggal_indonesia(NOW(),false); ?>
                  </span>
            </li>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-envelope bg-blue"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> <?= jam_indonesia(NOW(),false) ?></span>

                <h3 class="timeline-header"><a href="#">Helpdesk</h3>

                <div class="timeline-body">
                   <p>&nbsp;&nbsp;&nbsp;Belum Ada Pertanyaan yang diajukan!</p>
                </div>
                <div class="timeline-footer">
                  
                </div>
              </div>
            </li>
            <!-- END timeline item -->
            <!-- timeline item --> 
                         
                        
                         
                      <?php endif; ?>
          <li><i class="fa fa-clock-o bg-gray"></i></li>  
          </ul>
          <br>
          
                 <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'user' ? 'selected' :''; ?> value="user">User</option>
                           <option <?= $this->input->get('f') == 'judul' ? 'selected' :''; ?> value="judul">Judul</option>
                           <option <?= $this->input->get('f') == 'konten' ? 'selected' :''; ?> value="konten">Konten</option>
                           <option <?= $this->input->get('f') == 'waktu' ? 'selected' :''; ?> value="waktu">Waktu</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/bantuan');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
      </div>
     </div>
    
    
   
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_bantuan').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/bantuan/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('bantuan', $('table.dataTable'));
  }); /*end doc ready*/
</script>